package com.rumplestilzken.mmpi2.data;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfDocument;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.rumplestilzken.mmpi2.data.scale.*;
import io.qt.widgets.QLineEdit;
import org.json.JSONObject;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ResultProcessor {

    public ResultProcessor(boolean isMale) {
        this.isMale = isMale;
    }

    boolean isMale = false;

    public String getJSONFromAnswers(List<QuestionData.QuestionAnswerData> answers) {
        JSONObject answerObject = new JSONObject();
        JSONObject scales = new JSONObject();
        List<Scale> scaleList = Scales.getScales();

        ScaleProcessor sp = new ScaleProcessor();
        answerObject.put("Profile Evaluation", sp.process(answers, scaleList, isMale));

        scaleList.stream().forEachOrdered(i -> {
//            JSONObject scale = new JSONObject();
            Map<String, String> map = new HashMap<>();
            map.put("description", i.getDescription());
            map.put("rawScore", Long.toString(i.getRawScore()));
            map.put("kScore", Long.toString(i.getkScore()));
            map.put("tScore", i.gettScore());
            map.put("index", Integer.toString(i.getIndex()));
//            scale.put(i.toString(), map);
            scales.put(i.toString(), map);
        });
        answerObject.put("scales", scales);

        JSONObject answerWrapper = new JSONObject();
        for(QuestionData.QuestionAnswerData answer : answers) {
            answerWrapper.put(Integer.toString(answer.getIndex()), answer.getAnswer() == null ? "?" : answer.getAnswer());
        }
        answerObject.put("Answers", answerWrapper);

        ObjectMapper objectMapper = new ObjectMapper();
        Object jsonObject = null;
        String prettyPrint = "";
        try {
            jsonObject = objectMapper.readValue(answerObject.toString(), Object.class);
            prettyPrint = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(jsonObject);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }

        return prettyPrint;
    }

    public boolean writePDFDocument(List<QuestionData.QuestionAnswerData> answers, String path) {
        List<Scale> scaleList = Scales.getScales();

        ScaleProcessor sp = new ScaleProcessor();
        double profileEvaluation = sp.process(answers, scaleList, isMale);
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(path));
            document.open();
            document.addTitle("MMPI-2");
            document.addSubject("MMPI-2");
            document.addAuthor("rumplestilzken");
            document.addCreator("rumplestilzken");

//            Paragraph preface = new Paragraph();
//            // We add one empty line
//            addEmptyLine(preface, 1);
//            // Lets write a big header
//            preface.add(new Paragraph("Title of the document"));
//
//            addEmptyLine(preface, 1);
//            // Will create: Report generated by: _name, _date
//            preface.add(new Paragraph(
//                    "Report generated by: " + System.getProperty("user.name") + ", " + new Date()));
//            addEmptyLine(preface, 3);
//            preface.add(new Paragraph(
//                    "This document describes something which is very important "));
//
//            addEmptyLine(preface, 8);
//
//            preface.add(new Paragraph(
//                    "This document is a preliminary version and not subject to your license agreement or any other agreement with vogella.com ;-)."));
//
//            document.add(preface);
//             Start a new page
            document.newPage();

            Anchor anchor = new Anchor("");
            anchor.setName("Anchor Name");
            Chapter chapter = new Chapter(new Paragraph(anchor), 1);
            Paragraph paragraph = new Paragraph("");
            Section section = chapter.addSection(paragraph);

            PdfPTable table = new PdfPTable(5);
            PdfPCell scale = new PdfPCell((new Phrase("Scale")));
            scale.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(scale);

            PdfPCell scaleDesc = new PdfPCell((new Phrase("Scale Description")));
            scaleDesc.setHorizontalAlignment(Element.ALIGN_CENTER);
//            scaleDesc.setColspan(2);
            table.addCell(scaleDesc);

            PdfPCell rawScore = new PdfPCell((new Phrase("Raw Score")));
            rawScore.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(rawScore);

            PdfPCell kScore = new PdfPCell((new Phrase("K Score")));
            kScore.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(kScore);

            PdfPCell tScore = new PdfPCell((new Phrase("T Score")));
            tScore.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(tScore);

            table.setHeaderRows(1);
            table.setWidths(new int[] {50, 230, 50, 50, 60});

            scaleList.forEach(currentScale -> {
                boolean modify = currentScale instanceof True || currentScale instanceof False || currentScale instanceof QuestionScale;

                String scaleId = currentScale.toString();
                if(currentScale.toString().startsWith("Mf"))
                {
                    scaleId = "Mf";
                }
                table.addCell(scaleId);

                if(modify)
                {
                    table.addCell(" ");
                }
                else
                {
                    table.addCell(currentScale.getDescription().isEmpty() ? " " : currentScale.getDescription());
                }

                table.addCell(Long.toString(currentScale.getRawScore()));
                table.addCell(Long.toString(currentScale.getkScore()).equals("-1") ? " " : Long.toString(currentScale.getkScore()));

                if(modify)
                {
                    table.addCell(" ");
                }
                else {
                    table.addCell(currentScale.gettScore());
                }

            });

            document.add(table);

            document.newPage();

            Paragraph peParagraph = new Paragraph("Profile Evaluation: " + profileEvaluation);
            document.add(peParagraph);

            StringBuilder answerString = new StringBuilder();
            for(int i = 0; i < answers.size()-1; i++){
                QuestionData.QuestionAnswerData a = answers.get(i);
                if(a == null) {
                    answerString.append("?");
                }
                else if(a.getAnswer()) {
                    answerString.append("T");
                }
                else if (!a.getAnswer()) {
                    answerString.append("F");
                }
            }

            Paragraph answerSummaryParagraph = new Paragraph("Answer Summary");
            Paragraph answerParagraph = new Paragraph(answerString.toString());
            document.add(answerSummaryParagraph);
            document.add(answerParagraph);

            document.close();
        } catch (DocumentException e) {
            throw new RuntimeException(e);
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }

        return true;
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}
